### ISSUE TITLE
模拟器编译出错

### ISSUE THREAD

**Issue by snoooopy** [Forairaaaaa/rachel_sdk_simulator#2]
我在Ubuntu18.04下编译模拟器，会报如下错误
![图片](https://github.com/Forairaaaaa/rachel_sdk_simulator/assets/20832172/43e4ba8b-c720-45b6-97c4-4b3d05f7eabd)
请问这是什么原因呢？

**Comment by Forairaaaaa** [comment]
看起来像是SDL版本比较低

**Comment by snoooopy** [comment]
> 看起来像是SDL版本比较低

是的，我开始是apt安装的，后来去官网下了源码安装，这个问题就解决了，感谢

**Comment by Forairaaaaa** [comment]
不客气~
